name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:

jobs:
  cmake:
    name: Build with CMake
    runs-on: ubuntu-latest
    container:
      image: docker.io/rootproject/root:6.26.06-ubuntu22.04

    steps:
      - name: dependencies
        run: |
          apt-get update
          apt-get install -y git
      - uses: actions/checkout@v3
      - name: CMake configure
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      - name: CMake build
        run: |
          cmake --build build
      - name: Run tests
        run: |
          cmake --build build --target tests
          ctest --test-dir build/tests --output-on-failure

  docker-publish:
    name: Publish Docker image
    runs-on: ubuntu-latest
    needs: cmake

    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CONTAINER_REGISTRY_GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          pull: true
          push: true
          tags: |
            ghcr.io/lobis/gas-cli:latest
